### PR TITLE
include release name and body in the output

### PR DESCRIPTION
**Pull request by maciejp**
as those parameters are useful when deploying applications. 

This PR includes a few other minor improvements, namely:
* adding a workflow for verifying that the action works as expected
* fixing the Readme by tagging `token` as required
* improve the descriptions of parameters in the Readme

### CODE REVIEW

**Comment by maciejp** [comment]
@dsaltares I don't know how (or if it's possible at all) to make this workflow run in this PR. You can check the result on [the PR I opened for my fork](https://github.com/maciejp/fetch-gh-release-asset/pull/2/checks?check_run_id=2507831545)

**Review by dsaltares — APPROVED** [review]
Thank you, we have some kind of CI!

**Comment by maciejp** [comment]
My pleasure! Any chance you could create a new release? I'm eager to remove a bunch of ugly CURLs from my actions :)

**Comment by maciejp** [comment]
@dsaltares ? :)

**Comment by maciejp** [comment]
Hi @dsaltares , would you find some time to create a new release? 🙂 
I already have a PR open in one of my company's projects that depends on this change.

**Pull request merged**
