### PR TITLE
Default value for token added

### LINKED ISSUE #31: Add default value for `token` argument
According to [this](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret) github documentation page, there is a default token already available in every workflow run. It is accessible vis `GITHUB_TOKEN` secret or `github.token` context.  
It may be a good idea to add this value as a default value for `token` argument as accessing this repository releases is to my mind one of the most common cases for this action.

### PR DESCRIPTION
**Pull request by pseusys**
Closes #31 issue

### CODE REVIEW

**Comment by dsaltares** [comment]
Are you sure this works?
Most actions that require the Github token force you to make it explicit. For example: https://github.com/marketplace/actions/godot-export#environment-variables.
IIRC I tested to default it and it didn't work.

**Comment by pseusys** [comment]
I'm not sure my code works, but I know and love [an action that uses github token imlicitly](https://github.com/marketplace/actions/deploy-to-github-pages).
And this is the code it uses: https://github.com/JamesIves/github-pages-deploy-action/blob/5a8b8e44c56b854f94bbb8d1e215518705b97a32/action.yml#L21-L32

**Comment by dsaltares** [comment]
Could you please make sure the action works with the implicit token?

**Comment by pseusys** [comment]
I've tried to run your test file without specifying token explicitly, here are the results: https://github.com/pseusys/fetch-gh-release-asset/actions/workflows/demo.yml

**Comment by dsaltares** [comment]
Thanks!

**Pull request merged**
