### PR TITLE
Turn 404 into warning

### LINKED ISSUE #26: Change asset missing from error into warning
Right now, if the asset is missing, an error is thrown:

> [!] Release asset not found
> Release data: {
>   "message": "Not Found",
>   "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-release-by-tag-name"
> }

I am in a situation where the asset isn't always there, so I'd like an option to suppress that error, or perhaps we could just always turn it into a warning?

If people's pipelines rely on the asset being there, then their pipelines would fail anyway later in the process.

### PR DESCRIPTION
**Pull request by ffMathy**
Fixes #26.

### CODE REVIEW

**Review by vojtapol — CHANGES_REQUESTED** [review]
The goal of this action is to download an asset. If the asset does not exist, the action should fail in my opinion. 

Also, this message is actually printed when the release itself cannot be found or accessed. It has nothing to do with the asset. The asset is checked on line 53.

**Comment by dsaltares** [comment]
I agree with @vojtapol. An action that downloads a release asset should fail when the release asset does not exist. That is a good default. If it is to do anything else, it should be via an option. However, I don't think that option should be added, for simplicity. 

Thanks for the PR though, it is appreciated.

**Comment by ffMathy** [comment]
@dsaltares I totally agree. Normally. The reason I opened it, is because composite actions in GitHub Actions couldn't have `if` clauses, so it was impossible to optionally run your step.

Now they just implemented `if` clauses in composite actions, so it's now possible.

**Comment by ffMathy** [comment]
Actually @dsaltares I was a bit quick there. It's still an issue. If clauses in composite actions can't solve it.

The dilemma is that I have a deploy flow which stores the built output as an artifact on the release, so that if the release is re-released (or edited), it can skip the build process because it has already been built.

This is because we want to roll back to previous releases quickly.

So I want a way to say "fetch this release if it exists, but don't fail the whole pipeline".

I don't want to wrap `if: failed()` in all of the rest of my steps in my composite action.

Would it be possible to have a flag that can bypass this at least?

**Comment by ffMathy** [comment]
Related issue (showing it's still not possible to run continue-on-error on composite actions): https://github.com/actions/runner/issues/1457

**Pull request closed without merging**
